### ISSUE TITLE
TLS support values not exposed

### ISSUE THREAD

**Issue by codyprashant** [eldada/postfix-relay-kubernetes#5]
I have been trying to enable TLS encryption on the provided helm chart but didnt got successful. Any suggestions how we are going to add the same in values.yaml

I have tried using below line in values.yam but still not working
postfixCustomConfig: "smtpd_tls_security_level = encrypt"

**Comment by eldada** [comment]
Can you exec into your container and see if the `POSTFIX_CUSTOM_CONFIG` is defined correctly?

**Comment by eldada** [comment]
I tried using your config example, and I can see insider the container the line 
```
smtpd_tls_security_level = encrypt
```
added to `/etc/postfix/main.cf`

**Comment by eldada** [comment]
I just found that the chart's `values.yaml` was missing the image tag with the support for the custom config (`0.5`).
I added. Can you test again with the latest chart sources?

**Comment by codyprashant** [comment]
Thanks for responding very quick... I have tested the changes and its seems now its trying to enable TLS but getting failed and throwing below error on postfix

2021-02-04T13:29:16.526069+00:00 postfix-relay-599c4899d7-zfrk2 postfix/smtpd[99]: warning: No server certs available. TLS won't be enabled

and the error I am receiving on my Java application is 

`smtp DEBUG: Attempting plain socket connection to server XXX.XX.XXX.XXX:587
220 my.host.local ESMTP Postfix
EHLO csapp-8d8784b95-5r62x
250-my.host.local
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 CHUNKING
smtp DEBUG: Processing extension PIPELINING
smtp DEBUG: Processing extension SIZE 10240000
smtp DEBUG: Processing extension VRFY
smtp DEBUG: Processing extension ETRN
smtp DEBUG: Processing extension STARTTLS
smtp DEBUG: Processing extension ENHANCEDSTATUSCODES
smtp DEBUG: Processing extension 8BITMIME
smtp DEBUG: Processing extension DSN
smtp DEBUG: Processing extension CHUNKING
smtp DEBUG: Successful connection
MAIL FROM: <AAAA@BBBB.com> SIZE=10359
530 5.7.0 Must issue a STARTTLS command first
QUIT
221 2.0.0 Bye
2021-02-04 05:31:09 [http-nio-8080-exec-93] [system] [Sara Adamson] ERROR - Error while sending mail to : "[ABCD <XXX@YYYY.com>]".
org.apache.geronimo.javamail.transport.smtp.SMTPSendFailedException: 5.7.0 Must issue a STARTTLS command first
        at org.apache.geronimo.javamail.transport.smtp.SMTPTransport.sendMessage(SMTPTransport.java:257) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]
        at javax.mail.Transport.send(Transport.java:95) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]
        at javax.mail.Transport.send(Transport.java:48) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]`


 Do you have any suggestions on this

**Comment by codyprashant** [comment]
Also please let me know if you have any suggestions resolving this error

> 2021-02-04T13:44:16.711923+00:00 postfix-relay-599c4899d7-9tj6l postfix/smtp[99]: warning: SASL authentication failure: No worthy mechs found
> 2021-02-04T13:44:16.711938+00:00 postfix-relay-599c4899d7-9tj6l postfix/smtp[99]: 6A66073BE04: SASL authentication failed; cannot authenticate to server email-smtp.us-west-2.amazonaws.com[10.250.121.128]: no mechanism available
> 2021-02-04T13:44:16.808369+00:00 postfix-relay-599c4899d7-9tj6l postfix/smtp[99]: warning: SASL authentication failure: No worthy mechs found

**Comment by slavoo** [comment]
Hi guys, this is very timely as I've just stumbled upon the same issue with "No worthy mechs found". It boils down to few packages missing from the container. @eldada, would you be able to merge and rebuild it? I'll submit the pull request in few minutes.

**Comment by eldada** [comment]
I merged the fix from @slavoo and released `eldada-docker-examples.bintray.io/postfix-relay:0.6`. 
I'd love feedback so we can close this if resolved.

**Comment by codyprashant** [comment]
Thanks for quick turnaround @eldada and also thanks to @slavoo for fixing SASL issue.

I am still facing the issue with enabling TLS. Below configuration is used 
postfixCustomConfig: "smtp_tls_security_level = encrypt; smtpd_tls_security_level = encrypt;"

Logs from postfix

> 2021-02-04T19:34:52.193462+00:00 postfix-relay-578c96676d-vggns postfix/smtpd[99]: warning: No server certs available. TLS won't be enabled

Logs from Java application using javamailer

> DEBUG: getProvider() returning provider protocol=smtp; type=javax.mail.Provider$Type@63e7b3c7; class=org.apache.geronimo.javamail.transport.smtp.SMTPTransport; vendor=Apache Software Foundation;version=1.0
> smtp DEBUG: Attempting plain socket connection to server XX.XX.XX.XX:587
> 220 my.host.local ESMTP Postfix
> EHLO app-8d8784b95-5r62x
> 250-my.host.local
> 250-PIPELINING
> 250-SIZE 10240000
> 250-VRFY
> 250-ETRN
> 250-STARTTLS
> 250-ENHANCEDSTATUSCODES
> 250-8BITMIME
> 250-DSN
> 250 CHUNKING
> smtp DEBUG: Processing extension PIPELINING
> smtp DEBUG: Processing extension SIZE 10240000
> smtp DEBUG: Processing extension VRFY
> smtp DEBUG: Processing extension ETRN
> smtp DEBUG: Processing extension STARTTLS
> smtp DEBUG: Processing extension ENHANCEDSTATUSCODES
> smtp DEBUG: Processing extension 8BITMIME
> smtp DEBUG: Processing extension DSN
> smtp DEBUG: Processing extension CHUNKING
> smtp DEBUG: Attempting to negotiate STARTTLS with server XX.XX.XX.XX
> STARTTLS
> 454 4.7.0 TLS not available due to local problem
> smtp DEBUG: STARTTLS command rejected by SMTP server XX.XX.XX.XX
> QUIT
> 221 2.0.0 Bye
> 2021-02-04 11:35:12 [http-nio-8080-exec-20] [system] [Sara Adamson] ERROR - Error while sending mail to : "[JABCD <abb@ddd.com>]".
> javax.mail.SendFailedException: Send failure (javax.mail.MessagingException: Unable to make TLS server connection)
>         at javax.mail.Transport.send(Transport.java:163) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]
>         at javax.mail.Transport.send(Transport.java:48) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]


FYI, I am using AWS EKS cluster where my Java app is also deployed in same kubernetes where postfix is also deployed but may be different nodes.

I am trying to send an email from my Java app using "geronimo-javamail_1.4_mail-1.8.4.jar" with "smtps.starttls.enable = true" property and this email will go to postfix which will relay to AWS SES which has TLS enabled by default.

**Comment by slavoo** [comment]
Hi, @eldada thanks for merging. I'll check it soon and let you know.

@codyprashant my best guess is that it's another package which may be needed. ca-certificates would you mind adding it in the Dockerfile and if it fixes your problem raising another the pull request?

I hope it helps.

**Comment by slavoo** [comment]
@eldade, I just tried on my side. Works like a charm. Thanks!

**Comment by codyprashant** [comment]
Sorry Guys, I am not having much experience working with Dockers and first time using postfix as well.

I need you guys help in fixing this TLSproblem. Can anyone of you please make the changes to include TLS certs in Docker.

**Comment by eldada** [comment]
@codyprashant - I pushed an image with `ca-certificates` installed as @slavoo suggested.
Can you pull and try it?
```
eldada-docker-examples.bintray.io/postfix-relay:0.6.1
```

If it works, I'll make an official commit with this change.

**Comment by eldada** [comment]
@codyprashant  - did you get a chance to check the image I published?

**Comment by eldada** [comment]
I released a new image
```
eldada.jfrog.io/docker/postfix-relay:0.7
```

Closing this issue for now
